{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# 알라딘 베스트셀러 페이지 정적 크롤링"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "!pip install bs4\n",
    "!pip install requests\n",
    "!pip install pandas\n",
    "!pip install openpyxl"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>title</th>\n",
       "      <th>link</th>\n",
       "      <th>discount</th>\n",
       "      <th>star_score</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>더 트릭컬</td>\n",
       "      <td>https://www.aladin.co.kr/shop/wproduct.aspx?It...</td>\n",
       "      <td>19,800원</td>\n",
       "      <td>10.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>흔한남매 20</td>\n",
       "      <td>https://www.aladin.co.kr/shop/wproduct.aspx?It...</td>\n",
       "      <td>15,120원</td>\n",
       "      <td>10.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>호의에 대하여</td>\n",
       "      <td>https://www.aladin.co.kr/shop/wproduct.aspx?It...</td>\n",
       "      <td>16,920원</td>\n",
       "      <td>8.4</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>절창</td>\n",
       "      <td>https://www.aladin.co.kr/shop/wproduct.aspx?It...</td>\n",
       "      <td>16,200원</td>\n",
       "      <td>9.3</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>체인소 맨 : 스페셜 에디션</td>\n",
       "      <td>https://www.aladin.co.kr/shop/wproduct.aspx?It...</td>\n",
       "      <td>16,200원</td>\n",
       "      <td>None</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>145</th>\n",
       "      <td>읽으면서 바로 써먹는 어린이 공포의 수학 퍼즐 1</td>\n",
       "      <td>https://www.aladin.co.kr/shop/wproduct.aspx?It...</td>\n",
       "      <td>11,700원</td>\n",
       "      <td>9.7</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>146</th>\n",
       "      <td>나 혼자만 레벨업 15</td>\n",
       "      <td>https://www.aladin.co.kr/shop/wproduct.aspx?It...</td>\n",
       "      <td>14,400원</td>\n",
       "      <td>None</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>147</th>\n",
       "      <td>이타미 준 나의 건축</td>\n",
       "      <td>https://www.aladin.co.kr/shop/wproduct.aspx?It...</td>\n",
       "      <td>20,700원</td>\n",
       "      <td>9.2</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>148</th>\n",
       "      <td>가공범</td>\n",
       "      <td>https://www.aladin.co.kr/shop/wproduct.aspx?It...</td>\n",
       "      <td>19,800원</td>\n",
       "      <td>9.2</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>149</th>\n",
       "      <td>여학교의 별 4</td>\n",
       "      <td>https://www.aladin.co.kr/shop/wproduct.aspx?It...</td>\n",
       "      <td>7,650원</td>\n",
       "      <td>9.9</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>150 rows × 4 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                           title  \\\n",
       "0                          더 트릭컬   \n",
       "1                        흔한남매 20   \n",
       "2                        호의에 대하여   \n",
       "3                             절창   \n",
       "4                체인소 맨 : 스페셜 에디션   \n",
       "..                           ...   \n",
       "145  읽으면서 바로 써먹는 어린이 공포의 수학 퍼즐 1   \n",
       "146                 나 혼자만 레벨업 15   \n",
       "147                  이타미 준 나의 건축   \n",
       "148                          가공범   \n",
       "149                     여학교의 별 4   \n",
       "\n",
       "                                                  link discount star_score  \n",
       "0    https://www.aladin.co.kr/shop/wproduct.aspx?It...  19,800원       10.0  \n",
       "1    https://www.aladin.co.kr/shop/wproduct.aspx?It...  15,120원       10.0  \n",
       "2    https://www.aladin.co.kr/shop/wproduct.aspx?It...  16,920원        8.4  \n",
       "3    https://www.aladin.co.kr/shop/wproduct.aspx?It...  16,200원        9.3  \n",
       "4    https://www.aladin.co.kr/shop/wproduct.aspx?It...  16,200원       None  \n",
       "..                                                 ...      ...        ...  \n",
       "145  https://www.aladin.co.kr/shop/wproduct.aspx?It...  11,700원        9.7  \n",
       "146  https://www.aladin.co.kr/shop/wproduct.aspx?It...  14,400원       None  \n",
       "147  https://www.aladin.co.kr/shop/wproduct.aspx?It...  20,700원        9.2  \n",
       "148  https://www.aladin.co.kr/shop/wproduct.aspx?It...  19,800원        9.2  \n",
       "149  https://www.aladin.co.kr/shop/wproduct.aspx?It...   7,650원        9.9  \n",
       "\n",
       "[150 rows x 4 columns]"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "from bs4 import BeautifulSoup\n",
    "import requests\n",
    "\n",
    "# 여러 페이지에서 정보 추출\n",
    "data = []\n",
    "for page_num in range(1, 4):  # 1~3페이지 크롤링\n",
    "    url = \"https://www.aladin.co.kr/shop/common/wbest.aspx?BranchType=1&BestType=Bestseller\"\n",
    "    response = requests.get(url)  # 요청 보내기\n",
    "    html = response.text # 응답 받은 HTML 문서\n",
    "    soup = BeautifulSoup(html, 'html.parser')  # BeautifulSoup으로 파싱\n",
    "    trees = soup.select('.ss_book_box > table')\n",
    "    \n",
    "    for tree in trees:\n",
    "        title = tree.select_one(\".bo3\").text\n",
    "        link = tree.select_one(\".bo3\").attrs['href']\n",
    "        discount = tree.select_one('.ss_p2').text\n",
    "        \n",
    "        star_tag = tree.select_one(\".star_score\")\n",
    "        star_score = star_tag.text if star_tag else None\n",
    "        \n",
    "        # 데이터를 리스트에 추가\n",
    "        data.append([title, link, discount, star_score])\n",
    "\n",
    "# DataFrame으로 변환\n",
    "import pandas as pd\n",
    "df = pd.DataFrame(data, columns=['title','link','discount', 'star_score'])\n",
    "df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "# pandas를 사용해 엑셀로 저장\n",
    "df.to_excel('aladin_bestseller_assignment_data.xlsx', index=False)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
